name: build
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
        submodules: true
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install --assume-yes python3-pip
    - name: Checkout makelove
      uses: actions/checkout@v2
      with:
        repository: pfirsich/makelove
        path: makelove
    - name: Install makelove
      run:
        pip3 install ./makelove
    - name: Build
      run: cd main && makelove
    - name: Release
      env:
        ARTIFACT_NAME_APPIMAGE: 'multiviewer-2.AppImage'
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: main/dist/appimage/${{ env.ARTIFACT_NAME_APPIMAGE }}
